package es.nom.juanfranciscoruiz.bitacora;

public enum Comandos {
	HELP, REPLACE, HOLAMUNDO, MAPA2LISTA, 
	EXTRACTDIGITS, EXTRACTDOUBLEFROMSTRING,	EXTRACTLONGFROMSTRING, COMPARACIONES, 
	PROCESADUMMIES, TROCEOCADENA, ELIMINAPARENTESIS, VALIDAFORMATO,
	ARRAYTOSTRING, OBJETOS, FECHAS, ALCANCE, DOSLISTAS, LISTACOMOATRIBUTO,OPTIONAL,
	LAMBDA, MEMORIA
}
